= Manipulating PDFs in Java with Apache PDFBox

== Table of Content

== Before we Start
For this paper, we will create a maven project to showcase different usages for the PDFBox library.
First set up a Java project with Maven in the IDE of your choice. To learn how to check out the  do that https://maven.apache.org/guides/getting-started/[official getting started with Maven guide].

Then we can add PDFBox to our project.
To do that, simply add the following to your Maven project's pom.xml in the *dependencies* section:

[source, xml]
----
<dependency>
    <groupId>org.apache.pdfbox</groupId>
    <artifactId>pdfbox</artifactId>
    <version>2.0.27</version>
</dependency>
----

Then reload your dependencies, and you're good to go.

== First Steps
Now that we've set up our project we can start working with PDFBox. Let's start by creating an empty PDF.

First we need to create a PDFDocument, this class basically embodies an entire PDF file.

[source, java]
----
// Create a new empty document
PDDocument myDocument = new PDDocument();
----

To populate our PDF with a page, we need to create one.

[source, java]
----
// Create a new page without content
PDPage blankPage = new PDPage();
----

Now we need to add the page to our document.

[source, java]
----
// Add the page to the document
myDocument.addPage(blankPage);
----

Finally, we need to save and close our PDF in order to actually create it.

[source, java]
----
// Save the document and close it
myDocument.save("MyFirstPDF.pdf");
myDocument.close();
----

Now you should find a file called *MyFirstPDF.pdf* in the root directory of your project.
If you open it, it should only contain a single empty page.
